### ISSUE TITLE
KioskLive not receiving data

### ISSUE THREAD

**Issue by abstractcoder** [mitchellhenke/bus_kiosk#1]
This may be a little premature but I saw this project show up in my feed and wanted to check it out.

I added my MCTS key and am attempting to access the url http://localhost:4000/?stop_ids=713

I see that `BusKiosk.RealTimePoller.refresh_predictions` is getting called, and `sorted_predictions` is being populated with data, but the `PubSub.broadcast` doesn't seem to be reaching `KioskLive` so no data is being displayed.

**Comment by mitchellhenke** [comment]
You may also have to change https://github.com/mitchellhenke/bus_kiosk/blob/master/config/config.exs#L12 and remove `Test` so it uses the real module that calls the API?

**Comment by abstractcoder** [comment]
That did it. Thanks, cool project!
